### ISSUE TITLE
Example of resiliency on the client side?

### ISSUE THREAD

**Issue by ScalaWilliam** [hseeberger/akka-sse#170]
One use case of EventSource is as a message queuing mechanism over HTTP. Only problem is some conditions that cause the stream to end and the user having to write his own code how to handle the failure without any guidance - requiring quite a bit of akka-http/streams knowledge.

There are some conditions to deal with such as:
* Connection is closed after some time, prompting the use of the <a href="https://www.w3.org/TR/eventsource/#processField">`retry`</a> field to reopen the connection (& if a 204 is given, the client would stop forever).
* An initial connection could return a 5xx.
* An automatic reconnection could return a 5xx for some time.

In the reconnection cases, since `akka-sse` provides a latest event `id`, <a href="https://www.w3.org/TR/eventsource/#last-event-id">`Last-Event-ID`</a> can be passed in as the header.

Has anyone implemented this or done this before?

EventSource client on Chrome for instance reconnects automatically on connection close as per spec. If initial connection fails then it will try to reconnect again and again.

**Update**: Turns out a lot of this is just part of the specification actually ;-)

**Comment by ScalaWilliam** [comment]
For example, on Node.js and in client-side, you just need this one line to be afforded all the resiliency that you want:

* https://github.com/Paul255/ActionFPS-DiscordBOT/blob/22c2ed866eaf823a2033139819714145e156d13f/bot.js#L14

**Comment by cgbaker** [comment]
I am connecting to an event stream, where the subscriber is an akka-fsm actor. I send out-of-band messages to the subscriber on these failures, and the subscriber schedules a message to retry the connection. (I also pass a custom `Connected` method, for helping the actor keep track of whether it is connected or not for utility purposes.)

The stream that I connect to (Marathon's event bus) does not provide `Last-Event-Id`, but if so, I think this pattern could be modified to persist the most recent `Last-Event-Id` and pass it to the connection call. 

My connection code is here: 
https://github.com/GalacticFog/gestalt-dcos/blob/d4cd3db8f682ff1e87268e0df47c81463875703c/app/com/galacticfog/gestalt/dcos/marathon/MarathonSSEClient.scala#L84

The handling code in the actor is in these three blocks: 
https://github.com/GalacticFog/gestalt-dcos/blob/d4cd3db8f682ff1e87268e0df47c81463875703c/app/com/galacticfog/gestalt/dcos/marathon/GestaltMarathonLauncher.scala#L693
(because the stream I consume unfortunately doesn't have `Last-Event-Id` semantics, I have to do an update when I reconnect to pick up anything that I missed)

**Comment by hseeberger** [comment]
Actually an implementation of a resilient reconnecting client has been part of this project but recently was moved to alpakka: https://github.com/akka/alpakka/pull/88

This ain't an issue, so I'll close this. Please continue the discussion, if needed, on Gitter.
