### ISSUE TITLE
The purpose of buffer limit in the `LineParser`

### ISSUE THREAD

**Issue by OlegIlyenko** [hseeberger/akka-sse#44]
Recently I was experimenting with `akka-sse` and implemented both server and client with it. An interesting thing about the server is that produces a lot of events very fast. Here is the route definition:

```scala
val route: Route =
  (path("numbers") & get) {
    complete(Source(() => Iterator.from(1) map toSse))
  }
```

Very quickly I discovered, that this blows up a client because the default limit is 8KiB and `LineParser` gets more data on push.

After I removed the buffer limit completely and measured the size of buffer on any given push, i discovered that it never gets bigger that 128KiB in size. Even after artificially making client very slow I could see the backpressure properly propagated up to the server and overall speed of processing (number generation on the server) slows down. During all of my experiments the buffer size was never higher than 128KiB.

So I started to wonder, what is the purpose of the buffer limit in `LineParser`. As far as I can tell from the code, this limit does not interact with the reactive-streams backpressure mechanism in any way. Also experiments shown, that there is another bounded buffer somewhere down the stack. This, together with reactive-streams backpressure mechanism, prevents uncontrolled data accumulation even without the limit in `LineParser`.

**Comment by hseeberger** [comment]
`bufferMaxSize` of `EventStreamUnmarshalling`, which gets passed to the `LineParser`, bounds the buffer used for scanning the data of a `HttpEntity` which is a `Source[ByteStream]`. This buffer is not at all related to Reactive Streams backpressure. It's needed, because `LineParser` uses a buffer for scanning the data which grows until it can find a line break. There should not be any unbounded buffers, hence the limit. In practice the default should fit, because usually SSE is used to signal events, not to carry huge payloads. But if you send more than 8kiB in a single data line of your event, you will be able to see the limit in action.

I'll improve the documentation. Thanks for asking.
