### ISSUE TITLE
Heartbeat alternative to EventPublisher

### ISSUE THREAD

**Issue by danielwegener** [hseeberger/akka-sse#50]
Currently one can provide its own Source[ServerSentEvent,_] to publish ServerSentEvents. But to support heart-beats the user needs to implement the abstract  `EventPublisher` (and thus breaking out of akka-streams).

As discussed at [gitter](https://gitter.im/hseeberger/akka-sse?at=5593b06bb4ce4e473250fef7) we could provide the heartbeat-feature as its own Flow such that users could use their own event sources and plug it into (suggestion) `withHeartbeat(source:Source[T:ToServerSentEvent]):Source[ServerSentEvent]` .

@jrudolph had the idea to simply create a flow from a tick source and a flexi merge or to otherwise try dynamic stages (still have too look them up).

**Comment by jrudolph** [comment]
It's called `AsyncStage` but it may not be documented yet. 

Scaladoc here: http://doc.akka.io/api/akka-stream-and-http-experimental/1.0/#akka.stream.stage.AsyncStage

Here's an example usage from an otherwise unrelated test: https://github.com/akka/akka/blob/release-2.3-dev/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncSpec.scala#L31

**Comment by danielwegener** [comment]
Uhm yeah async ;) , thanks for sharing!

**Comment by hseeberger** [comment]
Hmm ... that looks pretty complicated. I think I will simply create a flow from a graph that merges its single input source with a tick source.

**Comment by hseeberger** [comment]
@danielwegener, take a look at #51, in partcular 
https://github.com/hseeberger/akka-sse/blob/heartbeats/akka-sse/src/test/scala/de/heikoseeberger/akkasse/HeartbeatsSpec.scala#L37.

What do you think?

**Comment by hseeberger** [comment]
Closed by #51.
